# Performance Results: Matrix Multiplication & Multithreading

### we first import the module that we will be using. 

In [29]:
import threading
import time
import numpy as np

### Let consider a 3 by 3 Matrix A and B with integer value ranging from 0 to 9 

In [30]:
# Create a random 3 by 3 Integer Matrix A and B 
A = np.random.randint(10, size=(3,3))
print("matrix A = \n",A)
B = np.random.randint(10, size=(3,3))
print("matrix B = \n",B)

matrix A = 
 [[8 4 1]
 [4 9 6]
 [3 4 8]]
matrix B = 
 [[4 3 2]
 [3 8 6]
 [1 6 3]]


### Our resulting Matrix C is set to be the Zero Matrix of a 3 by 3.  

In [31]:
#Set Matrix C to be the Zero Matrix
C = np.zeros([3, 3], dtype = int)
print("matrix C = \n",C)

matrix C = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


## Single Thread Performance Results

### In the following code we call this class Thread1. This class will compute A x B and hold its resulting output in Matrix C. 

In [32]:
#create a threading class 
class Thread1(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name

    def run(self):
        print("Starting " + self.name + "\n")
        C[0][0] = A[0][0] * B[0][0] + A[0][1] * B[1][0] + A[0][2] * B[2][0]
        C[0][1] = A[0][0] * B[0][1] + A[0][1] * B[1][1] + A[0][2] * B[2][1]
        C[0][2] = A[0][0] * B[0][2] + A[0][1] * B[1][2] + A[0][2] * B[2][2]
        
        C[1][0] = A[1][0] * B[0][0] + A[1][1] * B[1][0] + A[1][2] * B[2][0]
        C[1][1] = A[1][0] * B[0][1] + A[1][1] * B[1][1] + A[1][2] * B[2][1]
        C[1][2] = A[1][0] * B[0][2] + A[1][1] * B[1][2] + A[1][2] * B[2][2]
        
        C[2][0] = A[2][0] * B[0][0] + A[2][1] * B[1][0] + A[2][2] * B[2][0]
        C[2][1] = A[2][0] * B[0][1] + A[2][1] * B[1][1] + A[2][2] * B[2][1]
        C[2][2] = A[2][0] * B[0][2] + A[2][1] * B[1][2] + A[2][2] * B[2][2]
        print("End " + self.name + "\n")


We will than start a timer. Where time.time() is counted in secound but since the resulting time will be small. We will mutiply the resulting time by 1000.

In [33]:
print("Using a single thread \n")
start = (time.time() * 1000)
thread1= Thread1(1, "Thread 1")
thread1.start()
thread1.join()
print("Execution Time: ", (time.time() * 1000) - start)
print(C)

Using a single thread 

Starting Thread 1

End Thread 1

Execution Time:  1.000244140625
[[ 45  62  43]
 [ 49 120  80]
 [ 32  89  54]]


## 2 - Threads Performance Results

### Here we reset the C matrix to be the zero matrix

In [34]:
# reset C back to the zero matrix
C = np.zeros([3, 3], dtype = int)
print(C)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##### The following code. We created two total threads class.
Thread2 have a total of 4 computation
Thread3 have a total of 5 computation
This is because 9 is that divied into a whole number.
Here we will test the result of using two threads. 

In [36]:
class Thread2(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name

    def run(self):
        # this thread will be assign do 4 computation
        print("Starting " + self.name + "\n")
        C[0][0] = A[0][0] * B[0][0] + A[0][1] * B[1][0] + A[0][2] * B[2][0]
        C[0][1] = A[0][0] * B[0][1] + A[0][1] * B[1][1] + A[0][2] * B[2][1]
        C[0][2] = A[0][0] * B[0][2] + A[0][1] * B[1][2] + A[0][2] * B[2][2]
        C[1][0] = A[1][0] * B[0][0] + A[1][1] * B[1][0] + A[1][2] * B[2][0]
        
        print("End " + self.name + "\n")


In [37]:
class Thread3(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name
    # this thread will have to do a additon computation since 9 / 2 have a reminder of 1
    # therefore 4 + 1
    def run(self):
        print("Starting " + self.name + "\n")
        C[1][1] = A[1][0] * B[0][1] + A[1][1] * B[1][1] + A[1][2] * B[2][1]
        C[1][2] = A[1][0] * B[0][2] + A[1][1] * B[1][2] + A[1][2] * B[2][2] 
        C[2][0] = A[2][0] * B[0][0] + A[2][1] * B[1][0] + A[2][2] * B[2][0]
        C[2][1] = A[2][0] * B[0][1] + A[2][1] * B[1][1] + A[2][2] * B[2][1]
        C[2][2] = A[2][0] * B[0][2] + A[2][1] * B[1][2] + A[2][2] * B[2][2]
        print("End " + self.name + "\n")


### In the following it show a result that is much slower then running a single thread. 

In [38]:
print("Using 2 threads \n")
start = (time.time() * 1000)
thread2 = Thread2(2, "Thread 2")
thread3 = Thread3(3, "Thread 3")
thread2.start()
thread3.start()
thread2.join()
thread3.join()
print("Execution Time: ", (time.time() * 1000) - start)
print(C)

Using 2 threads 

Starting Thread 2

End Thread 2

Starting Thread 3

End Thread 3

Execution Time:  1.00341796875
[[ 45  62  43]
 [ 49 120  80]
 [ 32  89  54]]


## Three Threads Performance Results

### Here we reset the C matrix to be the zero matrix. 

In [39]:
# reset C back to the zero matrix
C = np.zeros([3, 3], dtype = int)
print(C)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


The following code. We created three total thread class.
Thread4, Thread5, and Thread6 have a total of 3 computation to complete each. 

In [40]:
class Thread4(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name

    def run(self):
        # this thread will be assign do 3 computation
        print("Starting " + self.name + "\n")
        C[0][0] = A[0][0] * B[0][0] + A[0][1] * B[1][0] + A[0][2] * B[2][0]
        C[0][1] = A[0][0] * B[0][1] + A[0][1] * B[1][1] + A[0][2] * B[2][1]
        C[0][2] = A[0][0] * B[0][2] + A[0][1] * B[1][2] + A[0][2] * B[2][2]
        
        print("End " + self.name + "\n")

In [41]:
class Thread5(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name

    def run(self):
        # this thread will be assign do 3 computation
        print("Starting " + self.name + "\n")
        C[1][0] = A[1][0] * B[0][0] + A[1][1] * B[1][0] + A[1][2] * B[2][0]
        C[1][1] = A[1][0] * B[0][1] + A[1][1] * B[1][1] + A[1][2] * B[2][1]
        C[1][2] = A[1][0] * B[0][2] + A[1][1] * B[1][2] + A[1][2] * B[2][2]
        
        
        print("End " + self.name + "\n")

In [42]:
class Thread6(threading.Thread):
    def __init__(self, id, name):
        threading.Thread.__init__(self)
        self.id = id
        self.name = name

    def run(self):
        # this thread will be assign do 3 computation
        print("Starting " + self.name + "\n")
        C[2][0] = A[2][0] * B[0][0] + A[2][1] * B[1][0] + A[2][2] * B[2][0]
        C[2][1] = A[2][0] * B[0][1] + A[2][1] * B[1][1] + A[2][2] * B[2][1]
        C[2][2] = A[2][0] * B[0][2] + A[2][1] * B[1][2] + A[2][2] * B[2][2]
        print("End " + self.name + "\n")

### Like with the previous excution time. The following result is much slower then running a single thread. 

In [43]:
print("Using 3 threads \n")
start = (time.time() * 1000)
thread4= Thread4(4, "Thread 4")
thread5= Thread5(5, "Thread 5")
thread6= Thread6(6, "Thread 6")

thread4.start()
thread5.start()
thread6.start()
thread4.join()
thread5.join()
thread6.join()
print("Execution Time: ", (time.time() * 1000) - start)
print(C)

Using 3 threads 

Starting Thread 4

End Thread 4

Starting Thread 5

End Thread 5

Starting Thread 6

End Thread 6

Execution Time:  2.004150390625
[[ 45  62  43]
 [ 49 120  80]
 [ 32  89  54]]


## Performance Results Conclusion

The resulting time when using multiple threads seem to be slower than running on a single thread. After further investigation, Python threading module only let one execution to run at a time. What it's happening here is that each execution is occurring, and threads are switching to one another. This makes the resulting execution time of multiple threads much slower than single thread.                                                                                                                          [Reference(Rossum & Drake Jr)]